name: justedlev-msrv
services:
  config.justedlev.io:
    tty: true
    env_file:
      - .env
    container_name: config-center
    image: justedlev/config-center:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ../config.d:${SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATION}
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 512MB
